export default {
  CHANGE_SELECTED: 'game/CHANGE_SELECTED',
  CLOSE_SELECTED: 'game/CLOSE_SELECTED',
  DONE: 'game/DONE',
  RELOAD_TILES: 'game/RELOAD_TILES',
  SELECTED_TILE: 'game/SELECTED_TILE',
};
